In [1]:
import pandas as pd
import re
import numpy as np

# Load the CSV file
df = pd.read_csv('rent.csv')
df

,Price,Pid,Property_name,Address
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos
...,...,...,...,...
9848,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos
9849,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos
9850,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos
9851,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos
9852,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...

In [120]:
print(df.iloc[1,2])

3 bedroom Flat / Apartment for rent Gerrard Gerard road Ikoyi Lagos

In [3]:
# Check columns, data types, and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9853 entries, 0 to 9852
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          9853 non-null   object
 1   Pid            9853 non-null   object
 2   Property_name  9853 non-null   object
 3   Address        9853 non-null   object
dtypes: object(4)
memory usage: 308.0+ KB

In [4]:
# Basic statistics
df.describe()

,Price,Pid,Property_name,Address
count,9853,9853,9853,9853
unique,388,9850,4762,5945
top,"1,000,000",G0258,3 bedroom Flat / Apartment for rent Lekki Phas...,Akoka Akoka Yaba Lagos
freq,289,2,103,122

In [5]:
no_bedroom_mask = ~df['Property_name'].str.contains(r'\d+\s*bedroom', case=False, na=False)
non_bedroom_rows = df[no_bedroom_mask]
non_bedroom_rows

,Price,Pid,Property_name,Address
6,"300,000 / year",H5142,Self Contain for rent Akoka Abule-Oja Yaba Lagos,Yaba Akoka Abule Oja Yaba Lagos
11,"7,000",H5831,Shop for rent Fola Agoro Yaba Lagos,Fola Agoro Fola Agoro Yaba Lagos
13,"500,000",H5826,Office Space for rent GRA Phase 2 Beside Karis...,GRA Phase 2 Beside Karis school Magodo Kosofe ...
27,"1,500,000 / year",H5778,300.0 square meter Flat / Apartment for rent A...,Alagomeji Alagomeji Yaba Lagos
37,"250,000 / year",H5751,Flat / Apartment for rent Shomolu Shomolu Lagos,off Bajulaiye road Shomolu Shomolu Lagos
...,...,...,...,...
9808,"2,000,000 / year","95,F1643",95.0 square meter Office Space for rent Opebi ...,igbasan street Opebi Ikeja Lagos
9820,"250,000,000",F1561,1500.0 square meter Land for rent Victoria Isl...,Oniru Victoria Island Extension Victoria Islan...
9823,"140,000,000",F1557,600.0 square meter Land for rent Lekki Phase 1...,lekki phase 1 Lekki Phase 1 Lekki Lagos
9837,"30,000 / sqm","355,F1466",355.0 square meter Office Space for rent Marin...,Marina Marina Marina Lagos Island Lagos
9845,"250,000",F1447,Self Contain for rent Fola Agoro Yaba Lagos,Fola Agoro Fola Agoro Yaba Lagos

In [6]:
non_bedroom_rows.iloc[0:60,2]

6       Self Contain for rent Akoka Abule-Oja Yaba Lagos
11                   Shop for rent Fola Agoro Yaba Lagos
13     Office Space for rent GRA Phase 2 Beside Karis...
27     300.0 square meter Flat / Apartment for rent A...
37       Flat / Apartment for rent Shomolu Shomolu Lagos
41           Self Contain for rent Shomolu Shomolu Lagos
43     Flat / Apartment for rent Adeola Odeku Victori...
48                        Shop for rent Akoka Yaba Lagos
73            Self Contain for rent Abule-Oja Yaba Lagos
74            Self Contain for rent Abule-Oja Yaba Lagos
79            Self Contain for rent Abule-Oja Yaba Lagos
151    Office Space for rent 1004 Ligali Ayorinde Vic...
152                  Shop for rent Shomolu Shomolu Lagos
153                  Shop for rent Shomolu Shomolu Lagos
154                  Shop for rent Fola Agoro Yaba Lagos
155                  Shop for rent Fola Agoro Yaba Lagos
158          Duplex for rent Oniru Victoria Island Lagos
162    Office Space for rent Off medical road, Obafem...
163      Office Space for rent GRA Ikeja GRA Ikeja Lagos
164          Office Space for rent Ikeja GRA Ikeja Lagos
167    Self Contain for rent Mayfair Garden Estate Aw...
169       Office Space for rent Awolowo Road Ikoyi Lagos
192     Self Contain for rent Bode Thomas Surulere Lagos
193    Flat / Apartment for rent Adeola Odeku Victori...
203    Land for rent Off Lekki-Epe Expressway Ajah Lagos
207    Commercial Property for rent Shomolu Shomolu L...
219    90.0 square meter Commercial Property for rent...
222               Self Contain for rent Onike Yaba Lagos
240                  Shop for rent Shomolu Shomolu Lagos
245          Self Contain for rent Onipanu Ilupeju Lagos
258           Self Contain for rent Abule-Oja Yaba Lagos
260    170.0 square meter Commercial Property for ren...
263           Self Contain for rent Abule-Oja Yaba Lagos
284            Bungalow for rent Abule-Ijesha Yaba Lagos
295    Commercial Property for rent Omole phase 1 Ogb...
301            Self Contain for rent Oke-Afa Isolo Lagos
306    Office Space for rent Lagos Island Lagos Islan...
319              Shop for rent Cement Cement Agege Lagos
327           Office Space for rent Alagomeji Yaba Lagos
343           Self Contain for rent Abule-Oja Yaba Lagos
361             Office Space for rent Berger Ojodu Lagos
383             Office Space for rent Berger Ojodu Lagos
425    167.0 square meter Office Space for rent PALM ...
430    Self Contain for rent Off bode thomas Bode Tho...
433    Self Contain for rent UNILAG,HERBERT MaCAULAY ...
436    90.0 square meter Commercial Property for rent...
451    554.25 square meter Land for rent Ifako-gbagad...
465    200.0 square meter Duplex for rent Anthony Vil...
468    883.5 square meter Office Space for rent Lekki...
474       Office Space for rent Osapa london Lekki Lagos
476    600.0 square meter Land for rent Free Trade Zo...
484    200.0 square meter Flat / Apartment for rent O...
513    Self Contain for rent Lekki ph 1 Lekki Phase 1...
529    Commercial Property for rent Fadeyi Jibowu Yab...
531                 Shop for rent iwaya Onike Yaba Lagos
537    Self Contain for rent Adeola Odeku Victoria Is...
538    1320.0 square meter Office Space for rent Off ...
545    Self Contain for rent Off Bajulaiye road Shomo...
585    136.0 square meter Office Space for rent Apapa...
590    300.0 square meter Duplex for rent Mobolaji Ba...
Name: Property_name, dtype: object

In [7]:
#mport pandas as pd
#import numpy as np

# extract number before "bedroom"
bedroom_numbers = df['Property_name'].str.extract(r'(\d+)\s*bedroom', flags=re.IGNORECASE)

df['Bedrooms'] = np.where(
    bedroom_numbers[0].notna(),
    bedroom_numbers[0],  # case 1: has number of bedrooms
    np.where(
        df['Property_name'].str.contains('self contain', case=False, na=False),
        'self contain',  # case 2: self contain
        'commercial/incomplete data'  # case 3: everything else
    )
)
df

,Price,Pid,Property_name,Address,Bedrooms
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1
...,...,...,...,...,...
9848,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1
9849,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3
9850,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2
9851,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3
9852,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8

In [8]:
df['Bedrooms'].value_counts()

Bedrooms
3                             3967
2                             1750
4                             1207
1                             1156
commercial/incomplete data     790
5                              593
self contain                   232
6                               67
7                               38
10                              35
8                               14
9                                4
Name: count, dtype: int64

In [9]:
# checking rows that has the commercial or incomplete data
rows_ci = df[df['Bedrooms'] == 'commercial/incomplete data']
rows_ci

,Price,Pid,Property_name,Address,Bedrooms
11,"7,000",H5831,Shop for rent Fola Agoro Yaba Lagos,Fola Agoro Fola Agoro Yaba Lagos,commercial/incomplete data
13,"500,000",H5826,Office Space for rent GRA Phase 2 Beside Karis...,GRA Phase 2 Beside Karis school Magodo Kosofe ...,commercial/incomplete data
27,"1,500,000 / year",H5778,300.0 square meter Flat / Apartment for rent A...,Alagomeji Alagomeji Yaba Lagos,commercial/incomplete data
37,"250,000 / year",H5751,Flat / Apartment for rent Shomolu Shomolu Lagos,off Bajulaiye road Shomolu Shomolu Lagos,commercial/incomplete data
43,"5,000,000",H1845,Flat / Apartment for rent Adeola Odeku Victori...,Adeola Odeku street Adeola Odeku Victoria Isl...,commercial/incomplete data
...,...,...,...,...,...
9782,"20,000 / sqm","70,F1808",Office Space for rent Off Awolowo Road Ikoyi L...,Off Awolowo Road Ikoyi Lagos,commercial/incomplete data
9808,"2,000,000 / year","95,F1643",95.0 square meter Office Space for rent Opebi ...,igbasan street Opebi Ikeja Lagos,commercial/incomplete data
9820,"250,000,000",F1561,1500.0 square meter Land for rent Victoria Isl...,Oniru Victoria Island Extension Victoria Islan...,commercial/incomplete data
9823,"140,000,000",F1557,600.0 square meter Land for rent Lekki Phase 1...,lekki phase 1 Lekki Phase 1 Lekki Lagos,commercial/incomplete data
9837,"30,000 / sqm","355,F1466",355.0 square meter Office Space for rent Marin...,Marina Marina Marina Lagos Island Lagos,commercial/incomplete data

In [10]:
# sample of the commercial or incomplete data
rows_ci.iloc[5:65,2]

48                        Shop for rent Akoka Yaba Lagos
151    Office Space for rent 1004 Ligali Ayorinde Vic...
152                  Shop for rent Shomolu Shomolu Lagos
153                  Shop for rent Shomolu Shomolu Lagos
154                  Shop for rent Fola Agoro Yaba Lagos
155                  Shop for rent Fola Agoro Yaba Lagos
158          Duplex for rent Oniru Victoria Island Lagos
162    Office Space for rent Off medical road, Obafem...
163      Office Space for rent GRA Ikeja GRA Ikeja Lagos
164          Office Space for rent Ikeja GRA Ikeja Lagos
169       Office Space for rent Awolowo Road Ikoyi Lagos
193    Flat / Apartment for rent Adeola Odeku Victori...
203    Land for rent Off Lekki-Epe Expressway Ajah Lagos
207    Commercial Property for rent Shomolu Shomolu L...
219    90.0 square meter Commercial Property for rent...
240                  Shop for rent Shomolu Shomolu Lagos
260    170.0 square meter Commercial Property for ren...
284            Bungalow for rent Abule-Ijesha Yaba Lagos
295    Commercial Property for rent Omole phase 1 Ogb...
306    Office Space for rent Lagos Island Lagos Islan...
319              Shop for rent Cement Cement Agege Lagos
327           Office Space for rent Alagomeji Yaba Lagos
361             Office Space for rent Berger Ojodu Lagos
383             Office Space for rent Berger Ojodu Lagos
425    167.0 square meter Office Space for rent PALM ...
436    90.0 square meter Commercial Property for rent...
451    554.25 square meter Land for rent Ifako-gbagad...
465    200.0 square meter Duplex for rent Anthony Vil...
468    883.5 square meter Office Space for rent Lekki...
474       Office Space for rent Osapa london Lekki Lagos
476    600.0 square meter Land for rent Free Trade Zo...
484    200.0 square meter Flat / Apartment for rent O...
529    Commercial Property for rent Fadeyi Jibowu Yab...
531                 Shop for rent iwaya Onike Yaba Lagos
538    1320.0 square meter Office Space for rent Off ...
585    136.0 square meter Office Space for rent Apapa...
590    300.0 square meter Duplex for rent Mobolaji Ba...
604    90.0 square meter Office Space for rent Alagom...
610    Flat / Apartment for rent Chevy view estate ch...
641          Office Space for rent Pako Akoka Yaba Lagos
643                       Shop for rent Akoka Yaba Lagos
676    Office Space for rent Adeniran Ogunsanya Surul...
749                Shop for rent Ogunlana Surulere Lagos
753         Commercial Property for rent Sabo Yaba Lagos
754    Commercial Property for rent osborne Osborne F...
759    550.0 square meter Commercial Property for ren...
767    Office Space for rent off Lateef Salami Ajao E...
791    50.0 square meter Flat / Apartment for rent Ag...
839    Office Space for rent Mobolaji Bank Anthony Wa...
854    240.0 square meter Commercial Property for ren...
874    Office Space for rent Adeniran Ogunsanya Surul...
876    Office Space for rent Off Adeola Odeku Adeola ...
890    Office Space for rent Awoyokun Coker Road Ilup...
904    Commercial Property for rent lekki phase 1 Lek...
906    Office Space for rent Victoria Island Victoria...
919    Commercial Property for rent LEKKI PHASE 1 Lek...
929    900.0 square meter Office Space for rent Adeol...
931    Commercial Property for rent Allen Avenue Ikej...
936    Commercial Property for rent Oregun Oregun Ike...
938    Commercial Property for rent Ikosi Oregun Ikej...
Name: Property_name, dtype: object

In [11]:
#df = df[df['Bedrooms'] != 'commercial/incomplete data']
#df
df = df.drop(df[df['Bedrooms'] == 'commercial/incomplete data'].index).reset_index(drop=True)
df

,Price,Pid,Property_name,Address,Bedrooms
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1
...,...,...,...,...,...
9058,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1
9059,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3
9060,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2
9061,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3
9062,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8

In [12]:
df['Bedrooms'].value_counts()

Bedrooms
3               3967
2               1750
4               1207
1               1156
5                593
self contain     232
6                 67
7                 38
10                35
8                 14
9                  4
Name: count, dtype: int64

In [13]:
# making self contain as 0 as number of bedroom

df['Bedrooms'] = pd.to_numeric(df['Bedrooms'].replace('self contain', 0))
df['Bedrooms'].value_counts()

Bedrooms
3     3967
2     1750
4     1207
1     1156
5      593
0      232
6       67
7       38
10      35
8       14
9        4
Name: count, dtype: int64

In [14]:
df['Bedrooms'].value_counts()

Bedrooms
3     3967
2     1750
4     1207
1     1156
5      593
0      232
6       67
7       38
10      35
8       14
9        4
Name: count, dtype: int64

In [15]:
# Extract the word before 'lagos' and create a new column named Locality

df['Locality'] = df['Address'].str.extract(r'(\w+)\s+Lagos\s*$', flags=re.IGNORECASE)
df

,Price,Pid,Property_name,Address,Bedrooms,Locality
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1,Ajah
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3,Ikoyi
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1,Yaba
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2,Surulere
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1,Yaba
...,...,...,...,...,...,...
9058,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1,Yaba
9059,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3,Yaba
9060,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2,Yaba
9061,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3,Ogudu
9062,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8,Surulere

In [16]:
df['Locality'].unique()

array(['Ajah', 'Ikoyi', 'Yaba', 'Surulere', 'Ikosi', 'Shomolu', 'Ilupeju',
       'Lekki', 'Odofin', 'Gbagada', 'Ikeja', 'Isolo', 'Ogba', 'Ikorodu',
       'Ojodu', 'Mushin', 'Island', 'Ogudu', 'Maryland', 'Sangotedo',
       'Alimosho', 'Okota', 'Idimu', 'Agege', 'Egba', 'Ojota', 'Ipaja',
       'Igando', 'Orile', 'Oshodi', 'Apapa', '1', 'Kosofe', 'Ejigbo',
       'Badagry', 'Lagos', 'Ojo', 'Berger', 'Ketu'], dtype=object)

In [17]:
conditions = [
    # 1. self contain + Bedrooms == 0
    (df['Property_name'].str.contains('self contain', case=False, na=False)) & (df['Bedrooms'] == 0),

    # 2. mini flat
    df['Property_name'].str.contains('mini flat', case=False, na=False),

    # 3. flat
    df['Property_name'].str.contains('flat', case=False, na=False),

    # 4. duplex
    df['Property_name'].str.contains('duplex', case=False, na=False),

    # 5. bungalow
    df['Property_name'].str.contains('bungalow', case=False, na=False),

    # 6. house
    df['Property_name'].str.contains('house', case=False, na=False),
]

choices = [
    'self contain',
    'mini flat',
    'flat',
    'duplex',
    'bungalow',
    'house'
]

df['Property_type'] = np.select(conditions, choices, default='other')
df

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1,Ajah,mini flat
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3,Ikoyi,flat
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1,Yaba,mini flat
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2,Surulere,flat
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1,Yaba,mini flat
...,...,...,...,...,...,...,...
9058,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1,Yaba,mini flat
9059,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3,Yaba,flat
9060,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2,Yaba,flat
9061,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3,Ogudu,duplex
9062,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8,Surulere,duplex

In [54]:
df['Property_type'].unique()

array(['mini flat', 'flat', 'self contain', 'duplex', 'house', 'bungalow',
       'other'], dtype=object)

In [56]:
rows_dd = df[df['Property_type'] == 'other']
rows_dd

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type
110,"10,000,000 / year",H5678,4 bedroom Commercial Property for rent Lekki P...,Maruwa(2nd roundabout) Lekki Phase 1 Lekki Lagos,4,Lekki,other
132,"1,500,000",H5656,2 bedroom Office Space for rent Magodo GRA Mag...,Magodo GRA Magodo Kosofe Ikosi Lagos,2,Ikosi,other
194,"1,500,000",H5541,3 bedroom Office Space for rent Lawanson Ojuel...,Lawanson Ojuelegba Surulere Lagos,3,Surulere,other
280,"18,000,000",H5386,5 bedroom Commercial Property for rent BIshop ...,31A OJU OLOBUN STREET BIshop Oluwole Ahmadu Be...,5,Island,other
290,"450,000",H5375,3 bedroom Office Space for rent Agege Road Cem...,Agege Road Cement Agege Lagos,3,Agege,other
...,...,...,...,...,...,...,...
8865,"5,000,000 / year",F2269,6 bedroom Commercial Property for rent Egbeda ...,Along Egbeda Akonwonjo rpad Egbeda Alimosho Lagos,6,Alimosho,other
8937,"600,000 / year",F2016,2 bedroom Office Space for rent Palmgroove Sho...,Pedro Palmgroove Shomolu Lagos,2,Shomolu,other
8947,"3,000,000",F2001,2 bedroom Office Space for rent Palmgroove Sho...,Shipeolu Palmgroove Shomolu Lagos,2,Shomolu,other
8949,"800,000 / year",F1999,2 bedroom Office Space for rent Onipanu Shomol...,market street Onipanu Shomolu Lagos,2,Shomolu,other
9020,"2,500,000 / year",F1645,2 bedroom Office Space for rent Opebi Ikeja Lagos,Opebi road Opebi Ikeja Lagos,2,Ikeja,other

In [68]:
print("""
going through this column, we have bedroom number of comercial properties, and we are not building ML model
for commercial properties consequently should be dropped. something distinct is that in te column we also have bedroom 
numbers for self contain, in the contrary self contain apartment doesn't have bedrooms so it is a wrong data input and has to be dropped as well
""")
rows_dd.iloc[1:60,2]

going through this column, we have bedroom number of comercial properties, and we are not building ML model
for commercial properties consequently should be dropped. something distinct is that in te column we also have bedroom
numbers for self contain, in the contrary self contain apartment doesn't have bedrooms so it is a wrong data input and has to be dropped as well

132     2 bedroom Office Space for rent Magodo GRA Mag...
194     3 bedroom Office Space for rent Lawanson Ojuel...
280     5 bedroom Commercial Property for rent BIshop ...
290     3 bedroom Office Space for rent Agege Road Cem...
309     2 bedroom Office Space for rent Beside FRSC Bu...
431     7 bedroom Commercial Property for rent Ademola...
460     2 bedroom Office Space for rent Thomas estate ...
461     3 bedroom Office Space for rent Thomas estate ...
547     10 bedroom Office Space for rent Marina Marina...
676     2 bedroom Shop for rent Magodo-Shangisha Kosof...
705     3 bedroom Commercial Property for rent oniru V...
797     4 bedroom Commercial Property for rent Dolphin...
831     3 bedroom Commercial Property for rent M.M. In...
907     2 bedroom Commercial Property for rent mainlan...
998     3 bedroom Office Space for rent Excellent hote...
1028    10 bedroom Office Space for rent Off Toyin str...
1036    2 bedroom Self Contain for rent OSAPA Osapa lo...
1039    3 bedroom Office Space for rent Off Toyin stre...
1157    4 bedroom Office Space for rent Allen Round Ab...
1162    4 bedroom Office Space for rent Allen round ab...
1326    10 bedroom Commercial Property for rent Lekki ...
1349    3 bedroom Office Space for rent Off Mojidi Toy...
1379    2 bedroom Commercial Property for rent Eleganz...
1380    2 bedroom Office Space for rent Off Toyin stre...
1422    2 bedroom Self Contain for rent Estate V.G.C L...
1462    2 bedroom Commercial Property for rent Alagunt...
1473    10 bedroom Office Space for rent Adeola Odeku ...
1916    4 bedroom Office Space for rent Ajayi road Ogb...
1929    10 bedroom Office Space for rent Toyin street ...
1984    3 bedroom Commercial Property for rent agness ...
2190    4 bedroom Commercial Property for rent Agbara ...
2195    2 bedroom Office Space for rent Off Toyin stre...
2228    2 bedroom Commercial Property for rent aso roc...
2235    5 bedroom Office Space for rent Toyin street I...
2259    2 bedroom Office Space for rent Egbeda Egbeda ...
2296    2 bedroom Commercial Property for rent Ikota V...
2535    6 bedroom Office Space for rent Itire Itire Su...
2570    2 bedroom Commercial Property for rent Ifako-g...
2599    5 bedroom Office Space for rent Off T.F Kuboye...
2604    2 bedroom Office Space for rent Off Emma Abimb...
2605    10 bedroom Office Space for rent Admiralty Way...
2701    2 bedroom Self Contain for rent Dolphin Estate...
2714         2 bedroom Land for rent Medina Gbagada Lagos
2808    3 bedroom Office Space for rent Adelabu Adelab...
2846    3 bedroom Office Space for rent alagomeji Alag...
2858    4 bedroom Office Space for rent adeniyi jones ...
2914    4 bedroom Office Space for rent 7/8 Bustop Aja...
2938    6 bedroom Office Space for rent adeniyi jones ...
2965    3 bedroom Office Space for rent Oshoppey Bus S...
2970    4 bedroom Office Space for rent College Road I...
2972    5 bedroom Office Space for rent Oshoppey Bus S...
2979    3 bedroom Office Space for rent adeniyi jones ...
2994    3 bedroom Office Space for rent VI Adeola Odek...
3025    3 bedroom Office Space for rent Alagomeji Yaba...
3036    3 bedroom Office Space for rent Ikeja Bus Stop...
3076    10 bedroom Commercial Property for rent Akoka ...
3161    10 bedroom Commercial Property for rent Abule ...
3168    10 bedroom Office Space for rent Akoka Akoka Y...
3188    10 bedroom Commercial Property for rent Akoka ...
Name: Property_name, dtype: object

In [72]:
# drop rows with 'other' as it is a faulty data

df = df[df['Property_type'] != 'other'].reset_index(drop=True)
df

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1,Ajah,mini flat
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3,Ikoyi,flat
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1,Yaba,mini flat
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2,Surulere,flat
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1,Yaba,mini flat
...,...,...,...,...,...,...,...
8857,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1,Yaba,mini flat
8858,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3,Yaba,flat
8859,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2,Yaba,flat
8860,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3,Ogudu,duplex
8861,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8,Surulere,duplex

In [74]:
df['Locality'].unique()

array(['Ajah', 'Ikoyi', 'Yaba', 'Surulere', 'Ikosi', 'Shomolu', 'Ilupeju',
       'Lekki', 'Odofin', 'Gbagada', 'Ikeja', 'Isolo', 'Ogba', 'Ikorodu',
       'Ojodu', 'Mushin', 'Island', 'Ogudu', 'Maryland', 'Sangotedo',
       'Alimosho', 'Okota', 'Idimu', 'Agege', 'Egba', 'Ojota', 'Ipaja',
       'Igando', 'Orile', 'Oshodi', 'Apapa', '1', 'Kosofe', 'Ejigbo',
       'Lagos', 'Ojo', 'Badagry', 'Berger', 'Ketu'], dtype=object)

In [78]:
df[df['Locality'] == '1']

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type
1803,"3,000,000 / year",H2566,4 bedroom Flat / Apartment for rent Lekki Peni...,Hakeem Dickson Street Lekki Peninsula Estate ...,4,1,flat

In [80]:
df.iloc[1803,3]

' Hakeem Dickson Street Lekki Peninsula Estate 1 Lagos'

In [92]:
df['Locality'] = df['Locality'].replace('1', 'lekki')
df.iloc[1803,5]

'lekki'

In [94]:
df[df['Locality'] == 'Lagos']

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type
3529,"550,000 / year",G8154,3 bedroom Flat / Apartment for rent Lagos,Amule Ipaja Lagos Lagos,3,Lagos,flat

In [96]:
df.iloc[3529,3]

'Amule Ipaja Lagos Lagos'

In [100]:
df['Locality'] = df['Locality'].replace('Lagos', 'Ipaja')
df.iloc[3529,5]

'Ipaja'

In [106]:
row_island = df[df['Locality'] == 'Island']
row_island

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type
121,"4,500,000 / year",H5671,3 bedroom Flat / Apartment for rent Oniru Vict...,Off Palace Way Oniru Victoria Island Extension...,3,Island,flat
124,"4,500,000 / year",H5668,3 bedroom Flat / Apartment for rent Oniru Vict...,off Palace Way Oniru Victoria Island Extension...,3,Island,flat
149,"3,000,000",H5615,2 bedroom Flat / Apartment for rent Oniru Adem...,Oniru Ademola Adetokunbo Victoria Island Lagos,2,Island,flat
160,"7,000,000",H5597,4 bedroom Flat / Apartment for rent by Dideolu...,by Dideolu Estate Victoria Island Lagos,4,Island,flat
163,"4,000,000 / year",H3249,3 bedroom House for rent Private estate in Vic...,Private estate in Victoria Island Private esta...,3,Island,house
...,...,...,...,...,...,...,...
8773,"2,300,000 / year",F1883,2 bedroom Flat / Apartment for rent Victoria I...,"Oniru, VI Victoria Island Extension Victoria I...",2,Island,flat
8798,"7,000,000 / year",F1779,5 bedroom Duplex for rent Victoria Island Exte...,Oniru Palace road Victoria Island Extension Vi...,5,Island,duplex
8812,"4,500,000 / year",F1716,4 bedroom Flat / Apartment for rent Victoria I...,Oniru Victoria Island Extension Victoria Islan...,4,Island,flat
8832,"2,500,000 / year",F1559,2 bedroom Flat / Apartment for rent ONIRU ESTA...,OFF PALACE ROAD ONIRU ESTATE Victoria Island E...,2,Island,flat
8835,"3,500,000 / year",F1543,5 bedroom Duplex for rent Oniru estate Victori...,Off palace road Oniru estate Victoria Island E...,5,Island,duplex

In [108]:
row_island.iloc[1:60,3]

124     off Palace Way Oniru Victoria Island Extension...
149        Oniru Ademola Adetokunbo Victoria Island Lagos
160               by Dideolu Estate Victoria Island Lagos
163     Private estate in Victoria Island Private esta...
166                  Dideolu Estate Victoria Island Lagos
180                    Karimu Kotun Victoria Island Lagos
189        Elsie Femi Pearse Street Victoria Island Lagos
278         Oju Olobun Adeola Odeku Victoria Island Lagos
290     Oniru Victoria Island Extension Victoria Islan...
301       Idejo Street Adeola Odeku Victoria Island Lagos
351                  Cluster C 1004 Victoria Island Lagos
359     victoria Island off Ajose adeogun, V.I Victori...
368     Atlantic Beach Estate Oniru Victoria Island Ex...
369     Oniru Estate Oniru Victoria Island Extension V...
371     New Market Road Onru Victoria Island Extension...
434            Off Ahmadu Bello Way Victoria Island Lagos
436            off Ahmadu Bello Way Victoria Island Lagos
489     Off Adeola Odeku Street, Victoria Island Adeol...
608     Off Adeola Odeku Adeola Odeku Adeola Odeku Vic...
629     Oniru Victoria Island Extension Victoria Islan...
630     Oniru Victoria Island Extension Victoria Islan...
639     Oniru Victoria Island Extension Victoria Islan...
648     Oniru Victoria Island Extension Victoria Islan...
655     Oniru Victoria Island Extension Victoria Islan...
672     Off Idejo Street, Victoria island Lagos. adeol...
681     Lawani Oduoye street Oniru Victoria Island Ext...
682     Oniru Victoria Island Extension Victoria Islan...
702     moshood olugbani Ligali Ayorinde Victoria Isla...
703     Dideolu Estate Oniru Victoria Island Extension...
719     Victoria Island Victoria Island Victoria Islan...
724     Oniru Victoria Island Extension Victoria Islan...
725     Oniru Victoria Island Extension Victoria Islan...
747     Ademola Adetokunbo Victoria Island Ademola Ade...
765                           Oniru Victoria Island Lagos
766     Ihuntayo Street ONIRU Victoria Island Extensio...
772     Off Adeyemo Alakija Victoria Island Extension ...
784     Off Adeola Odeku Adeola Odeku Victoria Island ...
787     Karimu ikotun Victoria island Karimu Kotun Vic...
801            Off Oba Idowu, Oniru Victoria Island Lagos
804     Off Elegba Festival Drive, Off Oba idowu, Onir...
805     off Sanusi Fafunwa Sanusi Fafunwa Victoria Isl...
823     Off Palace Road, Oniru Victoria Island Extensi...
828     Off Palace Road, Oniru Victoria Island Extensi...
941       Idowu Taylor Idowu Taylor Victoria Island Lagos
988     Off Landbridge Avenue, oniru Estate. Oniru Est...
1000    Oniru Victoria Island Extension Victoria Islan...
1047      Kofo Abayomi Kofo Abayomi Victoria Island Lagos
1060    Behind Four Point Hotel Oniru Estate Victoria ...
1072       Mabogunje Road Off Oniru Victoria Island Lagos
1077      Idowu Taylor Idowu Taylor Victoria Island Lagos
1158    Oniru Oniru Victoria Island Extension Victoria...
1173    Emerald Court Dedeolu Estate Victoria Island E...
1176    Dedeolu Estate Off Ligali Ayorinde Victoria Is...
1179    Grace Court Dedeolu Estate Victoria Island Ext...
1180    Emerald Court Dedeolu Estate Victoria Island E...
1181    Dedeolu Estate Dedeolu Estate Victoria Island ...
1197    Oniru Estate Oniru Estate Victoria Island Exte...
1206    VI extention Off Ligali Ayorinde Ligali Ayorin...
1366    Oniru Victoria Island Extension Victoria Islan...
Name: Address, dtype: object

In [112]:
df['Locality'] = df['Locality'].replace('Island', 'Victoria island')
df[df['Locality'] == 'Victoria island']

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type
121,"4,500,000 / year",H5671,3 bedroom Flat / Apartment for rent Oniru Vict...,Off Palace Way Oniru Victoria Island Extension...,3,Victoria island,flat
124,"4,500,000 / year",H5668,3 bedroom Flat / Apartment for rent Oniru Vict...,off Palace Way Oniru Victoria Island Extension...,3,Victoria island,flat
149,"3,000,000",H5615,2 bedroom Flat / Apartment for rent Oniru Adem...,Oniru Ademola Adetokunbo Victoria Island Lagos,2,Victoria island,flat
160,"7,000,000",H5597,4 bedroom Flat / Apartment for rent by Dideolu...,by Dideolu Estate Victoria Island Lagos,4,Victoria island,flat
163,"4,000,000 / year",H3249,3 bedroom House for rent Private estate in Vic...,Private estate in Victoria Island Private esta...,3,Victoria island,house
...,...,...,...,...,...,...,...
8773,"2,300,000 / year",F1883,2 bedroom Flat / Apartment for rent Victoria I...,"Oniru, VI Victoria Island Extension Victoria I...",2,Victoria island,flat
8798,"7,000,000 / year",F1779,5 bedroom Duplex for rent Victoria Island Exte...,Oniru Palace road Victoria Island Extension Vi...,5,Victoria island,duplex
8812,"4,500,000 / year",F1716,4 bedroom Flat / Apartment for rent Victoria I...,Oniru Victoria Island Extension Victoria Islan...,4,Victoria island,flat
8832,"2,500,000 / year",F1559,2 bedroom Flat / Apartment for rent ONIRU ESTA...,OFF PALACE ROAD ONIRU ESTATE Victoria Island E...,2,Victoria island,flat
8835,"3,500,000 / year",F1543,5 bedroom Duplex for rent Oniru estate Victori...,Off palace road Oniru estate Victoria Island E...,5,Victoria island,duplex

In [114]:
df['Locality'].unique()

array(['Ajah', 'Ikoyi', 'Yaba', 'Surulere', 'Ikosi', 'Shomolu', 'Ilupeju',
       'Lekki', 'Odofin', 'Gbagada', 'Ikeja', 'Isolo', 'Ogba', 'Ikorodu',
       'Ojodu', 'Mushin', 'Victoria island', 'Ogudu', 'Maryland',
       'Sangotedo', 'Alimosho', 'Okota', 'Idimu', 'Agege', 'Egba',
       'Ojota', 'Ipaja', 'Igando', 'Orile', 'Oshodi', 'Apapa', 'lekki',
       'Kosofe', 'Ejigbo', 'Ojo', 'Badagry', 'Berger', 'Ketu'],
      dtype=object)

In [116]:
island = ['ajah', 'ikoyi', 'lekki', 'victoria island', 'sangotedo']

mainland = [
    'yaba', 'surulere', 'ikosi', 'shomolu', 'ilupeju', 'odofin',
    'gbagada', 'ikeja', 'isolo', 'ogba', 'ikorodu', 'ojodu',
    'mushin', 'ogudu', 'maryland', 'alimosho', 'okota', 'idimu',
    'agege', 'egba', 'ojota', 'ipaja', 'igando', 'orile',
    'oshodi', 'apapa', 'kosofe', 'ejigbo', 'ojo', 'badagry',
    'berger', 'ketu'
]
df['Locality_clean'] = df['Locality'].str.lower().str.strip()
def classify_area(loc):
    if loc in island:
        return 'island'
    elif loc in mainland:
        return 'mainland'
    else:
        return 'unknown'

df['Area'] = df['Locality_clean'].apply(classify_area)
df

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type,Locality_clean,Area
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1,Ajah,mini flat,ajah,island
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3,Ikoyi,flat,ikoyi,island
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1,Yaba,mini flat,yaba,mainland
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2,Surulere,flat,surulere,mainland
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1,Yaba,mini flat,yaba,mainland
...,...,...,...,...,...,...,...,...,...
8857,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1,Yaba,mini flat,yaba,mainland
8858,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3,Yaba,flat,yaba,mainland
8859,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2,Yaba,flat,yaba,mainland
8860,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3,Ogudu,duplex,ogudu,mainland
8861,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8,Surulere,duplex,surulere,mainland

In [118]:
df['Area'].unique()

array(['island', 'mainland'], dtype=object)

In [122]:
# cleaning price to be integer

df['Price']=df['Price'].str.replace(r'\D','',regex=True)
df['Price']=pd.to_numeric(df['Price'],errors='coerce')
df

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type,Locality_clean,Area
0,400000,H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1,Ajah,mini flat,ajah,island
1,14000000,G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3,Ikoyi,flat,ikoyi,island
2,200000,H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1,Yaba,mini flat,yaba,mainland
3,800000,H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2,Surulere,flat,surulere,mainland
4,300000,H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1,Yaba,mini flat,yaba,mainland
...,...,...,...,...,...,...,...,...,...
8857,400000,F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1,Yaba,mini flat,yaba,mainland
8858,800000,F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3,Yaba,flat,yaba,mainland
8859,1000000,F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2,Yaba,flat,yaba,mainland
8860,1500000,F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3,Ogudu,duplex,ogudu,mainland
8861,4000000,F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8,Surulere,duplex,surulere,mainland

In [130]:
print(df.duplicated().sum())
df[df.duplicated()]

2

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type,Locality_clean,Area
2999,1000000,G4171,3 bedroom Flat / Apartment for rent harmony es...,harmony estate Ifako Gbagada Gbagada Lagos,3,Gbagada,flat,gbagada,mainland
6324,1200000,G0258,2 bedroom Flat / Apartment for rent Allen Aven...,Off Majekodunmi street Allen Avenue Ikeja Lagos,2,Ikeja,flat,ikeja,mainland

In [132]:
df=df.drop_duplicates()
df

,Price,Pid,Property_name,Address,Bedrooms,Locality,Property_type,Locality_clean,Area
0,400000,H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1,Ajah,mini flat,ajah,island
1,14000000,G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3,Ikoyi,flat,ikoyi,island
2,200000,H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1,Yaba,mini flat,yaba,mainland
3,800000,H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2,Surulere,flat,surulere,mainland
4,300000,H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1,Yaba,mini flat,yaba,mainland
...,...,...,...,...,...,...,...,...,...
8857,400000,F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1,Yaba,mini flat,yaba,mainland
8858,800000,F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3,Yaba,flat,yaba,mainland
8859,1000000,F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2,Yaba,flat,yaba,mainland
8860,1500000,F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3,Ogudu,duplex,ogudu,mainland
8861,4000000,F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8,Surulere,duplex,surulere,mainland

In [136]:
df.to_csv('cleaned_data.csv', index=False)

In [134]:
# Use one-hot encoding for feature engineering(best practice

df = pd.get_dummies(df, columns=['Area'], drop_first=True)
df['Interaction'] = df['Area_island'] * df['Bedrooms']
df

KeyError: 'Area_island'

In [18]:
g#extracting property type

def extract_property_type(property_name):

    if pd.isna(property_name):
        return 'Other'
 
    name = str(property_name).lower()
    
    if 'self' in name and Bedrooms==0:
        return 'self contain'
 
    if 'mini flat' in name:
        return 'Mini Flat'
 
    if 'flat' in name:
        return 'Flat'
 
    if 'bungalow' in name:
        return 'Bungalow'
 
    if 'house' in name:
        return 'House'
 
    if 'duplex' in name:
        return 'Duplex'
 
    if 'mansion' in name:
        return 'Mansion'
 
    if 'penthouse' in name:
        return 'Penthouse'
 
    if 'studio' in name:
        return 'Studio'
 
    
    return 'Other'
 
df['Property_type'] = df['Property_name'].apply(extract_property_type)
df

NameError: name 'g' is not defined

In [ ]:
island
marina
opposite
around
beside
after
area
i
1
rent
road
village
by
off
street
of

In [ ]:
'''
there are unusual names identified in the column which has to be corrected,
they include:
town
island
oba
hitech
road
gra
opposite
around
beside
after
area
1
village
by
of
estate
lga
street
off
behinde

'''

In [ ]:
# FOR TOWN
df[df['locality'].str.contains('town', case=False, na=False)]

In [ ]:
# FOR ISLAND

# FOR OBA

#FOR HITECH
df[df['locality'].str.contains('island', case=False, na=False)]

In [ ]:
print(df.iloc[3916:2])
print(df.iloc[3916:3])

In [ ]:
# FOR OBA

In [ ]:
# FOR HITECH

In [ ]:
# FOR ROAD

In [ ]:
# FOR GRA

In [ ]:

opposite
around
beside
after
area
1
village
by
of
estate
lga
street
off
behinde

In [ ]:
# FOR OPPOSITE

In [ ]:
# FOR AROUND

In [ ]:
# FOR BESIDE

In [ ]:
# FOR AFTER

In [ ]:
# FOR AREA

In [ ]:
print(df.iloc[1174, 2])
print(df.iloc[1181, 2])
print(df.iloc[7023, 2])

In [ ]:
df.iloc[[1174, 1181, 7023], 3]

In [ ]:
# STEP 4: DEFINE THE PROPERTY TYPE CATEGORIES
# =============================================================================
# These are properties that legitimately have no bedrooms.
# We will label them with a descriptive category instead of a number.
NON_RESIDENTIAL_KEYWORDS = {
   # 'Self Contain'          : r'self\s*contain',
    'Shop'                  : r'\bshop\b',
    'Office'                : r'office\s*space',
    'Commercial Property'   : r'commercial\s*property',
    'Land'                  : r'\bland\b',
    'Warehouse'             : r'\bwarehouse\b',
    'Event Centre'          : r'event\s*cent(re|er)',
    'Studio'                : r'\bstudio\b',
}

def extract_bedroom_info(property_name):
    """
    Extracts bedroom count from a property name string.

    Strategy:
    ---------
    1. If a bedroom number is found (e.g. "3 bedroom"), return it as an integer.
    2. If the property is a known non-residential type (shop, office, etc.),
       return the category label string (e.g. "Self Contain").
    3. If neither applies (ambiguous / unrecognized), return "Unknown".

    Separating numeric bedrooms from category labels lets you:
    - Keep the column as a clean integer for residential properties.
    - Avoid losing the non-residential rows (they're still useful for
      price modeling and outlier detection).
    - Encode non-residential categories separately during ML preprocessing.

    Parameters
    ----------
    property_name : str

    Returns
    -------
    int | str  — bedroom count, a category label, or "Unknown"
    """
    if pd.isna(property_name):
        return "Unknown"

    text = str(property_name).lower().strip()

    # --- Priority 1: Extract bedroom number ---
    # Matches patterns like "3 bedroom", "3bedroom", "3 bedrooms"
    bedroom_match = re.search(r'(\d+)\s*bedrooms?', text)
    if bedroom_match:
        return int(bedroom_match.group(1))

    # --- Priority 2: Identify known non-residential types ---
    for label, pattern in NON_RESIDENTIAL_KEYWORDS.items():
        if re.search(pattern, text):
            return label

    # --- Priority 3: Fallback ---
    return "Unknown"

df['bedrooms'] = df['Property_name'].apply(extract_bedroom_info)
df

In [ ]:
df['bedrooms'].value_counts()

In [ ]:
# knowing what is contained in 'unknown' rows
rows_unknown = df[df['bedrooms'].str.contains('Unknown', case=False, na=False)]
rows_unknown
'''
from the table seen below, the property name has unknown number of bedrooms and has to be dropped together with commercial properties
N/B: We are predicting for residentuial properties, if we have to predict price commercial properties, we will build a different machine learning model,
but here the data available will cause the ML to overfit because it is small, we need to gather more data
'''

In [ ]:
# dropping commercial properties rows
'''
we are dropping non bedroom rows because they are not residential
but commercial properties. And the non residential data available in df is
little compare to the data without making the model biased but we are keeping self contain because it is residential though it doesnt
have number of bedroom
'''

#keeping rows with digits or self contain
df=df[
df['bedrooms'].astype(str).str.contains(r'\d',na=False)|
    (df['bedrooms'].str.lower()=='self contain')
]
df

In [ ]:
df['bedrooms'].value_counts()

In [ ]:
#making self contain as 0

df['bedrooms'] = df['bedrooms'].replace('Self Contain', '0')
df['bedrooms'] = df['bedrooms'].astype(int)
df['bedrooms'].value_counts()

In [ ]:
# Extract the word before 'lagos' and create a new column named Locality
df['locality'] = df['Address'].str.lower().str.extract(r'(\w+)\s+lagos', expand=False)
df

In [ ]:
#extracting property type

# STEP 3: DEFINE THE EXTRACTION FUNCTION
# =============================================================================
def extract_property_type(property_name):
    """
    Extracts and normalises the property type from a property listing name.
 
    Logic (in priority order):
    1. Check for 'mini flat' modifier first — it overrides the main type
       because a mini flat is a distinct sub-type of flat in Nigerian real estate
    2. Match the main property type keyword from the known list
    3. Return 'Other' if no known type is found
 
    Parameters
    ----------
    property_name : str
 
    Returns
    -------
    str — one of: 'Mini Flat', 'Flat', 'Duplex', 'Bungalow', 'House', 'Other'
    """
    if pd.isna(property_name):
        return 'Other'
 
    name = str(property_name).lower()
    bedroomss = str(Bedrooms).lower()
    
 
    # --- Priority 1: Mini Flat (must check before 'flat') ---
    # "mini flat" always signals a studio-like unit with smaller rooms
    if 'self' in name and Bedrooms==0:
        return 'self contain'
 
    # --- Priority 2: Main property type keywords ---
    # Order matters: check more specific terms before broader ones
    if 'mini flat' in name:
        return 'Mini Flat'
 
    if 'flat' in name:
        return 'Flat'
 
    if 'bungalow' in name:
        return 'Bungalow'
 
    if 'house' in name:
        return 'House'
 
    if 'duplex' in name:
        return 'Duplex'
 
    if 'mansion' in propertyy:
        return 'Mansion'
 
    if 'penthouse' in name:
        return 'Penthouse'
 
    if 'studio' in name:
        return 'Studio'
 
    # --- Fallback ---
    return 'Other'
 
 
# =============================================================================
# STEP 4: APPLY THE FUNCTION
# =============================================================================
df['property_type'] = df['Property_name'].apply(extract_property_type)
df

In [ ]:
filtered_rows = df[
    (df['property_type'].str.contains('self contain', case=False, na=False)) &
    (df['bedrooms'] != 0)
]
filtered_rows

In [ ]:
df['bedrooms'].info()

In [ ]:
pd.to_numeric(df['bedrooms'], errors='coerce')

In [ ]:
df['bedrooms'].value_counts()

In [ ]:
df['bedrooms'].dtype

In [ ]:
df['locality'].unique()

In [ ]:
town
island
town
road
gra
opposite
around
beside
after
area
1
village
by
of
estate
lga
street
off
behinde

In [ ]:
df['property_type'].unique()

In [ ]:
df['property_type'].value_counts()

In [ ]:
df['property_type'].value_counts()

In [ ]:

#df[df['property_type'].str.contains('other', na=False)]
dff=df[df['property_type'].str.lower() == 'other']
dff

In [ ]:
rows_exact = df[df['property'].str.lower() == 'other']

In [ ]:
df['locality'].str.contains(r'\d').sum()

In [ ]:
df[df['locality'].str.contains(r'\d', na=False)]

In [ ]:
df.iloc[1959,3]

In [ ]:
df.iloc[1959,2]

In [ ]:
df['bedrooms'] = df['bedrooms'].replace('1', 'ikoyi')
df.iloc[df.iloc[1959,3]1959]

In [ ]:
df['locality'].value_counts()

In [ ]:
tt
df['Bedroom'].isna().sum()

In [ ]:
df['Price']=df['Price'].str.replace(r'\D','',regex=True)
df['Price']=pd.to_numeric(df['Price'],errors='coerce')
df

In [ ]:
# Extract the word before 'lagos'
df['Locality'] = df['Address'].str.lower().str.extract(r'(\w+)\s+lagos', expand=False)
df

In [ ]:
df['Locality'].isna().sum()

In [ ]:
df['Locality'].value_counts()

In [ ]:
# =============================================================================
# STEP 3: UNDERSTAND THE NON-BEDROOM ROWS
# =============================================================================
# Before extracting, let's categorize what types of properties exist
no_bedroom_mask = ~df['Property_name'].str.contains(r'\d+\s*bedroom', case=False, na=False)
non_bedroom_rows = df[no_bedroom_mask]
 
#print(f"\nRows WITH bedrooms    : {(~no_bedroom_mask).sum()}")
#print(f"Rows WITHOUT bedrooms : {no_bedroom_mask.sum()}")
#print(f"\nSample of non-bedroom rows:")
#print(non_bedroom_rows['Property_name'].head(15).to_string())
 
no_bedroom_mask.sum()

In [ ]:
import pandas as pd
import re

# =============================================================================
# STEP 1: LOAD THE DATA
# =============================================================================
df = pd.read_csv('rent_csv.xls')  # Despite the .xls extension, it's actually a CSV

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nFirst 5 rows:")
print(df.head())


# =============================================================================
# STEP 2: INSPECT THE property_name COLUMN
# =============================================================================
print("\n--- Sample of Property_name column ---")
print(df['Property_name'].head(20).to_string())


# =============================================================================
# STEP 3: UNDERSTAND THE NON-BEDROOM ROWS
# =============================================================================
# Before extracting, let's categorize what types of properties exist
no_bedroom_mask = ~df['Property_name'].str.contains(r'\d+\s*bedroom', case=False, na=False)
non_bedroom_rows = df[no_bedroom_mask]

print(f"\nRows WITH bedrooms    : {(~no_bedroom_mask).sum()}")
print(f"Rows WITHOUT bedrooms : {no_bedroom_mask.sum()}")
print(f"\nSample of non-bedroom rows:")
print(non_bedroom_rows['Property_name'].head(15).to_string())


# =============================================================================
# STEP 4: DEFINE THE PROPERTY TYPE CATEGORIES
# =============================================================================
# These are properties that legitimately have no bedrooms.
# We will label them with a descriptive category instead of a number.
NON_RESIDENTIAL_KEYWORDS = {
    'Self Contain'          : r'self\s*contain',
    'Shop'                  : r'\bshop\b',
    'Office'                : r'office\s*space',
    'Commercial Property'   : r'commercial\s*property',
    'Land'                  : r'\bland\b',
    'Warehouse'             : r'\bwarehouse\b',
    'Event Centre'          : r'event\s*cent(re|er)',
    'Studio'                : r'\bstudio\b',
}


# =============================================================================
# STEP 5: WRITE THE EXTRACTION FUNCTION
# =============================================================================
def extract_bedroom_info(property_name):
    """
    Extracts bedroom count from a property name string.

    Strategy:
    ---------
    1. If a bedroom number is found (e.g. "3 bedroom"), return it as an integer.
    2. If the property is a known non-residential type (shop, office, etc.),
       return the category label string (e.g. "Self Contain").
    3. If neither applies (ambiguous / unrecognized), return "Unknown".

    Separating numeric bedrooms from category labels lets you:
    - Keep the column as a clean integer for residential properties.
    - Avoid losing the non-residential rows (they're still useful for
      price modeling and outlier detection).
    - Encode non-residential categories separately during ML preprocessing.

    Parameters
    ----------
    property_name : str

    Returns
    -------
    int | str  — bedroom count, a category label, or "Unknown"
    """
    if pd.isna(property_name):
        return "Unknown"

    text = str(property_name).lower().strip()

    # --- Priority 1: Extract bedroom number ---
    # Matches patterns like "3 bedroom", "3bedroom", "3 bedrooms"
    bedroom_match = re.search(r'(\d+)\s*bedrooms?', text)
    if bedroom_match:
        return int(bedroom_match.group(1))

    # --- Priority 2: Identify known non-residential types ---
    for label, pattern in NON_RESIDENTIAL_KEYWORDS.items():
        if re.search(pattern, text):
            return label

    # --- Priority 3: Fallback ---
    return "Unknown"


# =============================================================================
# STEP 6: APPLY THE FUNCTION
# =============================================================================
df['bedrooms'] = df['Property_name'].apply(extract_bedroom_info)

print("\n--- New 'bedrooms' column (first 60 rows) ---")
print(df[['Property_name', 'bedrooms']].head(60).to_string())


# =============================================================================
# STEP 7: VERIFY THE RESULTS
# =============================================================================
print("\n--- Value counts for 'bedrooms' column ---")
print(df['bedrooms'].value_counts())

print("\n--- Data type distribution ---")
print("Numeric (int) rows:", df['bedrooms'].apply(lambda x: isinstance(x, int)).sum())
print("String label rows :", df['bedrooms'].apply(lambda x: isinstance(x, str)).sum())


# =============================================================================
# STEP 8: HOW TO HANDLE THESE IN A MACHINE LEARNING PIPELINE
# =============================================================================
# There are TWO recommended strategies. Choose based on your use case.

# -----------------------------------------------------------------------
# STRATEGY A: SPLIT INTO TWO SEPARATE COLUMNS
# Best for: when you want to model residential and commercial separately,
#           or when the non-residential rows are a small minority you want
#           to flag and isolate.
# -----------------------------------------------------------------------
df['bedroom_count'] = df['bedrooms'].apply(lambda x: x if isinstance(x, int) else None)
df['property_type'] = df['bedrooms'].apply(lambda x: x if isinstance(x, str) else 'Residential')

print("\n--- Strategy A: Two separate columns ---")
print(df[['Property_name', 'bedroom_count', 'property_type']].head(20).to_string())

# -----------------------------------------------------------------------
# STRATEGY B: ENCODE AS A SINGLE NUMERIC COLUMN WITH SENTINEL VALUES
# Best for: simple pipelines / tree-based models where you want ONE column.
# Non-residential types get assigned a special code BELOW the valid range
# (e.g. -1 for Unknown, -2 for Self Contain, etc.) so the model can
# distinguish them from real bedroom counts without dropping rows.
# -----------------------------------------------------------------------
SENTINEL_MAP = {
    'Self Contain'          : -1,
    'Shop'                  : -2,
    'Office'                : -3,
    'Commercial Property'   : -4,
    'Land'                  : -5,
    'Warehouse'             : -6,
    'Event Centre'          : -7,
    'Studio'                : -8,
    'Unknown'               : -9,
}

def to_numeric_sentinel(val):
    if isinstance(val, int):
        return val
    return SENTINEL_MAP.get(val, -9)

df['bedrooms_encoded'] = df['bedrooms'].apply(to_numeric_sentinel)

print("\n--- Strategy B: Single encoded column ---")
print(df[['Property_name', 'bedrooms_encoded']].head(20).to_string())
print("\nEncoded value counts:")
print(df['bedrooms_encoded'].value_counts().sort_index())


# =============================================================================
# STEP 9: SAVE THE CLEANED DATAFRAME
# =============================================================================
df.to_csv('rent_cleaned.csv', index=False)
print("\n✅ Saved to rent_cleaned.csv")
print("Final dataframe shape:", df.shape)
print("Final columns:", df.columns.tolist())

In [ ]:
h
# Extract House_type (text after bedroom up to '/')
df['House_type'] = df['Property_name'].str.extract(r'\d+\s*bedroom\s*([^/]+)', expand=False)

# Remove any leading/trailing spaces
df['House_type'] = df['House_type'].str.strip()
df

In [ ]:
# Load dataset
#df = pd.read_csv('/mnt/data/rent.csv')

# Standardize to lowercase (optional but safer)
df['House_type'] = df['House_type'].str.lower()

# Update only rows where 'duplex' is the first word
df.loc[df['House_type'].str.startswith('duplex', na=False), 'House_type'] = 'duplex'
df
# Preview result
#print(df[['Property_name', 'House_type']].head())

In [ ]:
df.iloc[4:50,5]

In [ ]:
df.iloc[31,2]

In [ ]:
df['Property_name'].str.contains('house for rent', case=False, na= False).sum()

In [ ]:
df['House_type'].value_counts()

In [ ]:
# Standardize to lowercase (optional but safer)
df['House_type'] = df['House_type'].str.lower()

# Update only rows where 'bungalow' is the first word
df.loc[df['House_type'].str.startswith('bungalow', na=False), 'House_type'] = 'bungalow'
df

In [ ]:
df['House_type'].value_counts()

In [ ]:
# Normalize text
df['Property_name_clean'] = df['Property_name'].str.lower()

# Function to classify property type
def get_property_type(text):
    if pd.isna(text):
        return None
    
    if 'mini flat Flat' in text:
        return 'mini flat'
    elif 'flat apartment' in text or 'flat' in text:
        return 'flat apartment'
    elif 'duplex' in text:
        return 'duplex'
    elif 'bungalow' in text:
        return 'bungalow'
    elif 'office space' in text:
        return 'office space'
    elif 'shop' in text:
        return 'shop'
    elif 'warehouse' in text:
        return 'warehouse'
    else:
        return 'other'

# Apply function
df['Property_type'] = df['Property_name_clean'].apply(get_property_type)
df

In [ ]:
df['Property_type'].value_counts()

In [ ]:
# Normalize text
df['Property_name_cleann'] = df['Property_name'].str.lower()

# Function to classify property type
def get_property_type(text):
    if pd.isna(text):
        return None
    
    if 'office' in text:
        return 'office'
    elif 'self contain' in text:
        return 'self cotain'
    elif 'land' in text:
        return 'land'
    elif 'commercial property' in text:
        return 'commercial property'
    elif 'ware house' in text:
        return 'ware house'
    elif 'shop' in text:
        return 'shop'
    elif 'bungalow' in text:
        return 'bungalow'
    elif 'duplex' in text:
        return 'duplex'
    elif 'flat' in text:
        return 'flat'
    elif 'house' in text:
        return 'house'
    else:
        return 'other'

# Apply function
df['Property_typee'] = df['Property_name_cleann'].apply(get_property_type)
df

#land
#commercial property
#mini shop
#shop

In [ ]:
df['Property_typee'].value_counts()

In [ ]:
#import pandas as pd

# List of keywords to exclude
keywords = ['house', 'flat', 'bungalow', 'duplex', 'warehouse', 'shop']

# Create a regex pattern: 'house|flat|bungalow|duplex|warehouse|shop'
pattern = '|'.join(keywords)

# Filter the DataFrame
# case=False makes it case-insensitive; na=False ensures missing values don't break the code
filtered_df = df[~df['Property_name'].str.contains(pattern, case=False, na=False)]

In [ ]:
filtered_df