In [1]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('rent.csv')

# Display first few rows
df.head()

,Price,Pid,Property_name,Address
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos

In [3]:
df

,Price,Pid,Property_name,Address
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos
...,...,...,...,...
9848,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos
9849,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos
9850,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos
9851,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos
9852,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...

In [7]:
# Check columns, data types, and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9853 entries, 0 to 9852
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          9853 non-null   object
 1   Pid            9853 non-null   object
 2   Property_name  9853 non-null   object
 3   Address        9853 non-null   object
dtypes: object(4)
memory usage: 308.0+ KB

In [9]:
# Basic statistics
df.describe()

,Price,Pid,Property_name,Address
count,9853,9853,9853,9853
unique,388,9850,4762,5945
top,"1,000,000",G0258,3 bedroom Flat / Apartment for rent Lekki Phas...,Akoka Akoka Yaba Lagos
freq,289,2,103,122

In [11]:
#import pandas as pd

# Load dataset
#df = pd.read_csv('/mnt/data/rent.csv')

# Extract number of bedrooms from Property_name
df['Bedroom'] = df['Property_name'].str.extract(r'(\d+)\s*bedroom', expand=False)

# Convert to numeric (optional but recommended)
df['Bedroom'] = pd.to_numeric(df['Bedroom'], errors='coerce')
df
# Preview result
#print(df[['Property_name', 'Bedroom']].head())#

,Price,Pid,Property_name,Address,Bedroom
0,"400,000 / year",H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1.0
1,"14,000,000 / year",G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3.0
2,"200,000 / year",H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1.0
3,"800,000 / year",H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2.0
4,"300,000 / year",H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1.0
...,...,...,...,...,...
9848,"400,000 / year",F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1.0
9849,"800,000",F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3.0
9850,"1,000,000 / year",F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2.0
9851,"1,500,000",F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3.0
9852,"4,000,000",F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8.0

In [13]:
df['Price']=df['Price'].str.replace(r'\D','',regex=True)
df['Price']=pd.to_numeric(df['Price'],errors='coerce')
df

,Price,Pid,Property_name,Address,Bedroom
0,400000,H1190,1 bedroom mini flat Flat / Apartment for rent ...,Fidiso Estate Abijo Ajah Lagos,1.0
1,14000000,G7398,3 bedroom Flat / Apartment for rent Gerrard Ge...,Gerrard Gerrard Gerard Road Ikoyi Lagos,3.0
2,200000,H5843,1 bedroom mini flat Flat / Apartment for rent ...,Obadia Akoka Yaba Lagos,1.0
3,800000,H1194,2 bedroom Flat / Apartment for rent Iju Ishaga...,surulere Iju Ishaga Road Gbaja Surulere Lagos,2.0
4,300000,H5842,1 bedroom mini flat Flat / Apartment for rent ...,Close to Unilag Abule Oja Yaba Lagos,1.0
...,...,...,...,...,...
9848,400000,F1443,1 bedroom mini flat Flat / Apartment for rent ...,Alagomeji Alagomeji Yaba Lagos,1.0
9849,800000,F1442,3 bedroom Flat / Apartment for rent Onike Yaba...,iwaya road Onike Yaba Lagos,3.0
9850,1000000,F1441,2 bedroom Flat / Apartment for rent Adekunle Y...,Herbert Macaulay way Adekunle Yaba Lagos,2.0
9851,1500000,F1433,3 bedroom Duplex for rent Off Chief Echegile S...,Off Chief Echegile Street Ogudu Orike Ogudu Lagos,3.0
9852,4000000,F1430,8 bedroom Duplex for rent babs Animashuam Bode...,Census close babs Animashuam Bode Thomas Surul...,8.0